backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "layouts/njk.njk",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "SEO Meta Title",
              name: "metaTitle",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Meta Description",
              name: "metaDesc",
              widget: "string",
              required: false,
            }
          - {
              label: "Post Feed Heading",
              name: "postsHeading",
              widget: "string",
              default: "Latest posts",
            }
          - {
              label: "Archive Link Text",
              name: "archiveButtonText",
              widget: "string",
              default: "See all posts",
            }
          - {
              label: "Social Image",
              name: "socialImage",
              widget: "image",
              required: false,
            }
          - {
              label: "Featured text",
              name: "featuredText",
              widget: "string",
              default: "TradeLlama applies creative thinking and machine learning to large volume trade data, so asset managers can better understand the behavior of portfolio managers.",
            }
          - {
              label: "First Image/Paragraph Block - Title",
              name: "firstIpbTitle",
              widget: "string"
            }
          - {
              label: "First Image/Paragraph Block - Text",
              name: "firstIpbText",
              widget: "string",
            }
          - {
              label: "First Image/Paragraph Block - Url Button",
              name: "firstIpbButtonUrl",
              widget: "string",
            }
          - {
              label: "First Image/Paragraph Image URL - Text",
              name: "firstIpbImageUrl",
              widget: "string",
              default: "/images/svg/whoweare.svg",
            }
          - {
              label: "Second Image/Paragraph Block - Title",
              name: "secondIpbTitle",
              widget: "string",
              default: "What we do",
            }
          - {
              label: "Second Image/Paragraph Block - Text",
              name: "secondIpbText",
              widget: "string",
              default: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate veli.",
            }
          - {
              label: "Second Image/Paragraph Image URL - Text",
              name: "secondIpbImageUrl",
              widget: "string",
            }
          - {
              label: "Second Image/Paragraph Block - Url Button",
              name: "secondIpbButtonUrl",
              widget: "string",
            }
      - name: "who-we-are"
        label: "Who we are"
        delete: false
        file: "src/pages/who-we-are.md"
        slug: "{{slug}}"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "layouts/whoweare.njk",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Image for title", name: "imageUrl", widget: "string" }
          - {
              label: "SEO Meta Title",
              name: "metaTitle",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Meta Description",
              name: "metaDesc",
              widget: "string",
              required: false,
            }
          - { label: "Featured text", name: "featuredText", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "First Image/Paragraph Block - Title",
              name: "firstIpbTitle",
              widget: "string",
            }
          - {
              label: "First Image/Paragraph Block - Text",
              name: "firstIpbText",
              widget: "markdown",
            }
          - {
              label: "First Image/Paragraph Image URL - Text",
              name: "firstIpbImageUrl",
              widget: "string",
            }
          - {
              label: "Second Image/Paragraph Block - Title",
              name: "secondIpbTitle",
              widget: "string",
            }
          - {
              label: "Second Image/Paragraph Block - Text",
              name: "secondIpbText",
              widget: "markdown",
            }
          - {
              label: "Second Image/Paragraph Image URL - Text",
              name: "secondIpbImageUrl",
              widget: "string",
            }
          - { label: "Bar Link - Text", name: "textBarText", widget: "string" }
          - { label: "Bar Link - Link", name: "linkBarLink", widget: "string" }
          - {
              label: "Bar Link - Image URL",
              name: "linkBarImageUrl",
              widget: "string",
            }
      - name: "what-we-do"
        label: "What we do"
        delete: false
        file: "src/pages/what-we-do.md"
        slug: "{{slug}}"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "layouts/whatwedo.njk",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Image for title", name: "imageUrl", widget: "string" }
          - {
              label: "SEO Meta Title",
              name: "metaTitle",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Meta Description",
              name: "metaDesc",
              widget: "string",
              required: false,
            }
          - { label: "Featured text", name: "featuredText", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "First Image/Paragraph Block - Title",
              name: "firstIpbTitle",
              widget: "string",
            }
          - {
              label: "First Image/Paragraph Block - Text",
              name: "firstIpbText",
              widget: "markdown",
            }
          - {
              label: "First Image/Paragraph Image URL - Text",
              name: "firstIpbImageUrl",
              widget: "string",
            }
          - {
              label: "Second Image/Paragraph Block - Title",
              name: "secondIpbTitle",
              widget: "string",
            }
          - {
              label: "Second Image/Paragraph Block - Text",
              name: "secondIpbText",
              widget: "markdown",
            }
          - {
              label: "Second Image/Paragraph Image URL - Text",
              name: "secondIpbImageUrl",
              widget: "string",
            }
          - { label: "Bar Link - Text", name: "textBarText", widget: "string" }
          - { label: "Bar Link - Link", name: "linkBarLink", widget: "string" }
          - {
              label: "Bar Link - Image URL",
              name: "linkBarImageUrl",
              widget: "string",
            }
      - name: "get-in-touch"
        label: "Get In Touch"
        delete: false
        file: "src/pages/get-in-touch.md"
        slug: "{{slug}}"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "layouts/who-we-are.njk",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Image for title", name: "imageUrl", widget: "string" }
          - {
              label: "SEO Meta Title",
              name: "metaTitle",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Meta Description",
              name: "metaDesc",
              widget: "string",
              required: false,
            }
          - {
              label: "Contact column one",
              name: "contactOne",
              widget: "string",
            }
          - {
              label: "Contact column two",
              name: "contactTwo",
              widget: "string",
            }
  - name: "generic_pages"
    label: "Generic Pages"
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}"
    create: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/page.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Image URL", name: "imageUrl", widget: "string" }
      - {
          label: "Permalink Override (Pattern: '/your-slug/index.html')",
          name: "permalink",
          widget: "string",
          required: false,
        }
      - {
          label: "SEO Meta Title",
          name: "metaTitle",
          widget: "string",
          required: false,
        }
      - {
          label: "SEO Meta Description",
          name: "metaDesc",
          widget: "string",
          required: false,
        }
      - {
          label: "Social Image",
          name: "socialImage",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    create: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "SEO Meta Title",
          name: "metaTitle",
          widget: "string",
          required: false,
        }
      - {
          label: "SEO Meta Description",
          name: "metaDesc",
          widget: "string",
          required: false,
        }
      - {
          label: "Social Image",
          name: "socialImage",
          widget: "image",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - { label: "Site Name", name: "name", widget: "string" }
          - { label: "Site Url", name: "url", widget: "string" }
          - { label: "Author Name", name: "authorName", widget: "string" }
          - {
              label: "Author Email Address",
              name: "authorEmail",
              widget: "string",
            }
          - {
              label: "Author Twitter Handle",
              name: "authorHandle",
              widget: "string",
              required: false,
            }
          - {
              label: "Footer Short Description",
              name: "shortDesc",
              widget: "string",
            }
          - {
              label: "Maximum Posts Per Page",
              name: "maxPostsPerPage",
              widget: "number",
              default: 5,
            }
          - {
              label: "Show Theme Credit",
              name: "showThemeCredit",
              widget: "boolean",
              default: true,
            }
          - {
              label: "Enable Third Party Comments Area",
              name: "enableThirdPartyComments",
              widget: "boolean",
              default: false,
            }
          - {
              label: "Payment Pointer (Web Monetization: https://bit.ly/2kTRI1b)",
              name: "paymentPointer",
              widget: "string",
            }
          - {
              label: "Favicon path (EG: /images/favicon.png)",
              name: "faviconPath",
              widget: "string",
            }
          - { label: "Linked Url", name: "linkedinUrl", widget: "string" }
          - { label: "Twitter Url", name: "twitterUrl", widget: "string" }
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - {
                  label: "Is url to external site?",
                  name: "external",
                  widget: "boolean",
                  required: false,
                }
              - {
                  label: "Is featured?",
                  name: "featured",
                  widget: "boolean",
                  required: false,
                }
      - label: "Theme Settings"
        name: "theme"
        delete: false
        file: "src/_data/tokens.json"
        fields:
          - label: "Size Scale"
            name: "size-scale"
            widget: "object"
            fields:
              - {
                  label: "Base Size",
                  name: "base",
                  widget: "string",
                  default: "1rem",
                }
              - {
                  label: "Ratio: 300",
                  name: "300",
                  widget: "string",
                  default: "0.8rem",
                }
              - {
                  label: "Ratio: 500",
                  name: "500",
                  widget: "string",
                  default: "1.25rem",
                }
              - {
                  label: "Ratio: 600",
                  name: "600",
                  widget: "string",
                  default: "1.56rem",
                }
              - {
                  label: "Ratio: 700",
                  name: "700",
                  widget: "string",
                  default: "1.95rem",
                }
              - {
                  label: "Ratio: 800",
                  name: "800",
                  widget: "string",
                  default: "2.44rem",
                }
              - {
                  label: "Ratio: 900",
                  name: "900",
                  widget: "string",
                  default: "3.05rem",
                }
              - {
                  label: "Max Size",
                  name: "max",
                  widget: "string",
                  default: "4rem",
                }
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields:
              - {
                  label: "Primary",
                  name: "primary",
                  widget: "string",
                  default: "hsl(208, 57%, 21%)",
                }
              - {
                  label: "Primary Shade (darker)",
                  name: "primary-shade",
                  widget: "string",
                  default: "hsl(208, 56%, 14%)",
                }
              - {
                  label: "Primary Glare (lighter)",
                  name: "primary-glare",
                  widget: "string",
                  default: "hsl(207, 57%, 31%)",
                }
              - {
                  label: "Highlight",
                  name: "highlight",
                  widget: "string",
                  default: "hsl(42, 98%, 77%)",
                }
              - {
                  label: "Light",
                  name: "light",
                  widget: "string",
                  default: "hsl(0, 0%, 100%)",
                }
              - {
                  label: "Mid",
                  name: "mid",
                  widget: "string",
                  default: "hsl(0, 0%, 80%)",
                }
              - {
                  label: "Dark",
                  name: "dark",
                  widget: "string",
                  default: "hsl(0, 0%, 20%)",
                }
              - {
                  label: "Slate",
                  name: "slate",
                  widget: "string",
                  default: "hsl(0, 0%, 25%)",
                }
          - label: "Fonts"
            name: "fonts"
            widget: "hidden"
            default:
              {
                "base": '"-apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, Helvetica, Arial, sans-serif, ''Apple Color Emoji'', ''Segoe UI Emoji'', ''Segoe UI Symbol''"',
                "serif": '"''Lora'', serif"',
              }
